Desktop version
hiromataba/Personal-Portfollio pull request #9
Opened 2021-06-10 07:56 UTC by hiromataba

This is the desktop version of my portfolio

2021-06-10 10:06 UTC, DeliceLydia requested changes
## Hi @hiromataba ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-10 10:06 UTC, DeliceLydia commented on style.css
> +
- [ ] Your page is not responsive now in the requirements use media queries
`@media screen and (min-width: 990px` 
`@media screen and (max-width: 1080px)`

2021-06-10 10:06 UTC, DeliceLydia commented on index.html
> +            <div class="about-section-contact">
- [ ] Check this section
![ab](https://user-images.githubusercontent.com/44745855/121505117-d6e42580-c9e2-11eb-8950-f4c5f6541019.png)

2021-06-10 10:06 UTC, DeliceLydia commented on index.html
> +            <div class="about-section-contact">
- [ ] Stick to the design as much as you can like margin

2021-06-10 16:01 UTC, Dipeshtwis requested changes
Hi @hiromataba, 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️

**_Check the comments under the review._**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

 - Also you can add media query for ipad version using `@media screen and (min-width: 768px) {
 ....
}
`

**_Also check the comments under the review_**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**

-------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-10 16:01 UTC, Dipeshtwis commented on style.css
> +@media screen and (max-width: 1080px) {
- [ ] This is breaking your design, it should be `991px` instead of `1080px`.

for now from `990px` to `1080px`, it look like this (there is no nav-items for now). Please change it accordingly.

![Screenshot from 2021-06-10 21-15-05](https://user-images.githubusercontent.com/22434660/121555883-028dfc80-ca31-11eb-841d-18918736a563.png)

2021-06-10 16:01 UTC, Dipeshtwis commented on style.css
> +@media screen and (min-width: 990px) {
[OPTIONAL] [Highly Recommended]

- In previous review there is little mistake that's why I'm making clear to you with optional mark.

The desktop version starts from 992px. So, you can change accordingly. (`min-width: 992px`)

2021-06-11 05:21 UTC, Dipeshtwis approved these changes
# Hi @hiromataba, 

### Status: Approved ✔️

:+1: The portfolio UI is well looking good. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Highly Recommended:
- Remove `value="hiro mataba"` from line 273 and `value="aganzemataba@gmail.com"` from 284 from index.html file as we don't want to put the default value, we will use value whatever we write in the input.


**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
-----

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Dipesh Kumar_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-11 07:27 UTC, merged